### ISSUE TITLE
Might be worth adding a dependency update via DependaBot?

### ISSUE THREAD

**Issue by gomzyakov** [avtocod/specs-php#17]
In the simplest case, it's just file `.github)/dependabot.ym`:

```yml
version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
```

Detailed documentation is here https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
